### ISSUE TITLE
No output after execution

### ISSUE THREAD

**Issue by h4rvey-g** [jumphone/SPRINT#30]
I run the script below but nothing comes out, nor error message. The output folder is empty.
```
python ~/biosoft/SPRINT-master/sprint/sprint_prepare.py -t /path/transcript_annotation.gtf /path/reference_genome.fa ~/miniconda3/envs/rnasoft/bin/bwa;
python ~/biosoft/SPRINT-master/sprint/sprint_main -1 /path/Breast_A1_1.fq.gz -2 ./Breast_A1_2.fq.gz -p 10 /path/reference_genome.fa /path/rnaedit_output /path/bwa /path/samtools
```
How should I fix this? Thanks.

**Comment by jumphone** [comment]
Please "gunzip" the fastq file.


Feng


On 10/8/2021 11:41，Howie ***@***.***> wrote：

I run the script below but nothing comes out, nor error message. The output folder is empty.

python ~/biosoft/SPRINT-master/sprint/sprint_prepare.py -t /path/transcript_annotation.gtf /path/reference_genome.fa ~/miniconda3/envs/rnasoft/bin/bwa;
python ~/biosoft/SPRINT-master/sprint/sprint_main -1 /path/Breast_A1_1.fq.gz -2 ./Breast_A1_2.fq.gz -p 10 /path/reference_genome.fa /path/rnaedit_output /path/bwa /path/samtools


How should I fix this? Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by h4rvey-g** [comment]
> Please "gunzip" the fastq file. Feng On 10/8/2021 11:41，Howie ***@***.***> wrote： I run the script below but nothing comes out, nor error message. The output folder is empty. python ~/biosoft/SPRINT-master/sprint/sprint_prepare.py -t /path/transcript_annotation.gtf /path/reference_genome.fa ~/miniconda3/envs/rnasoft/bin/bwa; python ~/biosoft/SPRINT-master/sprint/sprint_main -1 /path/Breast_A1_1.fq.gz -2 ./Breast_A1_2.fq.gz -p 10 /path/reference_genome.fa /path/rnaedit_output /path/bwa /path/samtools How should I fix this? Thanks. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

I've run gunzip and got the `.fa` files, but still nothing comes out. Is there a way that I can check error message?

**Comment by jumphone** [comment]
> > Please "gunzip" the fastq file. Feng On 10/8/2021 11:41，Howie _**@**_.***> wrote： I run the script below but nothing comes out, nor error message. The output folder is empty. python ~/biosoft/SPRINT-master/sprint/sprint_prepare.py -t /path/transcript_annotation.gtf /path/reference_genome.fa ~/miniconda3/envs/rnasoft/bin/bwa; python ~/biosoft/SPRINT-master/sprint/sprint_main -1 /path/Breast_A1_1.fq.gz -2 ./Breast_A1_2.fq.gz -p 10 /path/reference_genome.fa /path/rnaedit_output /path/bwa /path/samtools How should I fix this? Thanks. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> I've run gunzip and got the `.fa` files, but still nothing comes out. Is there a way that I can check error message?

1. It should be “fq” file (“fa” file is reference sequence).

2. Please directly use the binary file “sprint”. You can download it from https://github.com/jumphone/SPRINT/tree/master/bin. 

3. We have tested sprint using Linux system. Are you using Linux system?

**Comment by h4rvey-g** [comment]
Sorry for the late feedback (Server went down for a few days). The binary file works fine. Thank you.
